<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGmdqwex\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGmdqwex/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGmdqwex.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGmdqwex\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGmdqwex\appDevDebugProjectContainer([
    'container.build_hash' => 'Gmdqwex',
    'container.build_id' => 'c69bedcf',
    'container.build_time' => 1614933268,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGmdqwex');
