<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZskx2uq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZskx2uq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZskx2uq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZskx2uq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZskx2uq\appProdProjectContainer([
    'container.build_hash' => 'Zskx2uq',
    'container.build_id' => 'bf2ddded',
    'container.build_time' => 1614930072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZskx2uq');
